jobs:
  dev-deploy:
    uses: <organization/workflows/.github/workflows/deploy.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      environment: 'dev'
    secrets: inherit
  
  qa-deploy:
    needs: dev-deploy
    uses: <organization/workflows/.github/workflows/deploy.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      environment: 'qa'
    secrets: inherit
  
  release-deploy:
    needs: qa-deploy
    uses: <organization/workflows/.github/workflows/deploy.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      environment: 'release'
    secrets: inherit
  
  prod-deploy:
    needs: release-deploy
    uses: <organization/workflows/.github/workflows/deploy.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      environment: 'prod'
    secrets: inherit
